### ISSUE TITLE
Missing References

### ISSUE THREAD

**Issue by ThinkingInXyZ** [Ludde321/PlanetMaker#2]
Hello, 

First of all, thanks for the project. I think it is quite nice idea. I tried to compile it but there are some missing references. Could you provide more information about dependencies?  

Also, I notice that the data for the planets are not included. Could you tell us how to get that data?

Thanks in advance! 
Ting

**Comment by Ludde321** [comment]
Thanks for showing some interest in my project. The only external reference is to Magick.NET.Core-Q8 and  I plan to remove it in the near future. Please provide some compile error/logs.

**Comment by Ludde321** [comment]
Regarding the datasets its true that they are not included. They are way to big for github, but I plan to describe where and how to download them in the wiki section.

**Comment by Ludde321** [comment]
Reference to ImageMagick is now removed.

**Comment by ThinkingInXyZ** [comment]
@Ludde321, you didnt even give me time to thank you for your first reply.  Very Fast even removing the reference to ImageMagick.
I will check your new version of the code.  
Really, Thank you very much!  Muchisimas Gracias! 

Kind Regards,
Ting
